# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/chore_planner_db
spring.datasource.username=root
spring.datasource.password=Pranav@2006

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server port
server.port=8082
